services:
  accounts:
    image: "ianklebold/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banknetwork
  loans:
    image: "ianklebold/loans:v1"
    container_name: loans-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banknetwork
  cards:
    image: "ianklebold/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banknetwork
networks:
  banknetwork:
    driver: "bridge"

